# Course 3: The NumPy package

## Motivation

NumPy (Numerical Python) is the core package for scientific computations in Python. It supports vectors and multidimensional matrices (tensors), functions for random number generation, linear algebra, signal processing, basic stats, etc. NumPy is a standard used by other packages. The manipulated data must fit RAM memory. NumPy relies on  C compiled code. 

In many situations data can be converted to numbers:
* an image in grey can be seen as a 2d matrix; every number is the intensity of the corresponding pixel  (0 - black, 255 - white)
![Imagine minsi scalata 0-1](./images/mnist_image.png)
* a colour image can be seen as a 3d matrix, of represented as RGB: the "parallel" matrices are representing a colour channel:
![Imagine RGB descompusa in 3 canale](./images/channelsrgb.gif)
* an audio file can be seen as one or more vectors, where the number of vectors is the number of recoring channels. For a wav file, the values represent membrane's displacement, sampled in time:
![sunet](./images/sound.png)
* a text can be translated in numerical vectors by using techniques as [Bag of words](https://en.wikipedia.org/wiki/Bag-of-words_model), [Word2vec](https://en.wikipedia.org/wiki/Word2vec), or any other type of embedding.

Vector and matrix representation used by NumPy is much more efficient than Python lists. The NumPy code actually uses native libraries, not interpreted code. If you vectorize you code, the efficiency is even greater on actual CPUs. 

The basic data type from NumPy is `ndarray` - n-dimensional array. 

## Creating arrays

In [1]:
# importing numpy, traditionally aliased as np
import numpy as np

# create a vector starting from a Python list
x = np.array([1, 4, 2, 5, 3])

# printing x's type
print(type(x)) 

# all the elements in the array are of the same type
print(x.dtype) 

# you can explicitely specify the underlying type in the array
y = np.array([1, 2, 3], dtype=np.float16)
print(y.dtype)

<class 'numpy.ndarray'>
int32
float16


In [2]:
# useful functions
all_zeros = np.zeros(10, dtype=int)
print(all_zeros)
# printing number of elements on each dimension (axis)
print(all_zeros.shape)

[0 0 0 0 0 0 0 0 0 0]
(10,)


In [3]:
# 2d matrix
mat = np.array([[1, 2, 3], [4, 5, 6]])  # note we start from lists of lists
print(mat)
print(mat.shape)
print(mat[0, 1])

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [4]:
# matrix with same value:
mat_7 = np.ones((4, 10)) * 7
print(mat_7)

mat_7_2 = np.full((4, 10), 7)

print(mat_7 == mat_7_2)

[[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]]
[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


The number of dimensions of a matrix is given by:

In [5]:
print('Number of dimensions of all_zeros:', all_zeros.ndim)
print('Number of dimensions of mat:', mat.ndim)

Number of dimensions of all_zeros: 1
Number of dimensions of mat: 2


The total number of elements, byte size of an element are found as:

In [6]:
print('mat size: {0}\nmat element size: {1} bytes\nmat.dtype:{2}'.format(mat.size, mat.itemsize, mat.dtype))

mat size: 6
mat element size: 4 bytes
mat.dtype:int32


In [7]:
# usefull cases
all_ones = np.ones((3, 5))

print(all_ones)
all_pi = np.full((3, 2), np.pi)

print(all_pi)
print(np.eye(3))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14159265 3.14159265]
 [3.14159265 3.14159265]
 [3.14159265 3.14159265]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# equally spaced values in an interval; the interval bounds are part of the vector
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [9]:
# arange works identically with Python's range function
some_values = np.arange(0, 10, 3)
print(some_values)
print(type(some_values))

[0 3 6 9]
<class 'numpy.ndarray'>


In [10]:
# random numbers
x = np.random.random((2, 3))
print(x)

[[0.75976309 0.16261257 0.97336502]
 [0.09168004 0.61604223 0.05257277]]


Tipurile de date folosibile pentru ndarrays sunt:

| Type  | Explanation |
| ---- | -----------|
| bool_ | 	Boolean (True or False) stored as a byte | 
| int_ | 	Default integer type (same as C long; normally either int64 or int32) | 
| intc | 	Identical to C int (normally int32 or int64) | 
| intp | 	Integer used for indexing (same as C ssize_t; normally either int32 or int64) | 
| int8 | 	Byte (-128 to 127) | 
| int16 | 	Integer (-32768 to 32767) | 
| int32 | 	Integer (-2147483648 to 2147483647) | 
| int64 | 	Integer (-9223372036854775808 to 9223372036854775807) | 
| uint8 | 	Unsigned integer (0 to 255) | 
| uint16 | 	Unsigned integer (0 to 65535) | 
| uint32 | 	Unsigned integer (0 to 4294967295) | 
| uint64 | 	Unsigned integer (0 to 18446744073709551615) | 
| float_ | 	Shorthand for float64. | 
| float16 | 	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa | 
| float32 | 	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa | 
| float64 | 	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa | 
| complex_ | 	Shorthand for complex128. | 
| complex64 | 	Complex number, represented by two 32-bit floats (real and imaginary components) | 
| complex128 | 	Complex number, represented by two 64-bit floats (real and imaginary components) |

A popular operation is taking an array and changing its shape:

In [11]:
# from a vector to a matrix
vec = np.arange(10)
mat = vec.reshape(2, 5)
print(vec)
print(mat)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
#...and vice versa:
vec2 = mat.flatten()
print(vec2)

[0 1 2 3 4 5 6 7 8 9]


Matrices can be concatenated; the concatenation dimension (axis) should be specified:

In [13]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)

In [14]:
# vertical concatenation (stacking)
vertical = np.concatenate((a, b), axis=0)
print(vertical)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


The axis concept is defined for matrices with at least two dimensions. For a 2D matrix, the axis 0 sweeps the matrix vertically, while axis 1 sweeps it horizontally.

In [15]:
# horizontal concatenation
horizontal = np.concatenate((a, b), axis=1)
print(horizontal)

[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [16]:
# same as:
vertical = np.vstack((a, b))
horizontal = np.hstack((a, b))
print(vertical)
print(horizontal)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [17]:
matrix = np.arange(15).reshape(3, 5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [18]:
sum_by_columns= np.sum(matrix, axis=0)
print(sum_by_columns)

[15 18 21 24 27]


In [19]:
sum_by_rows= np.sum(matrix, axis=1)
print(sum_by_rows)

[10 35 60]


## Operating with ndarrays

As expected, the basic operations from linear algebra are already implemented.

In [20]:
# multiplying by a scalar
a = np.array([[1, 2, 3], [4, 5, 6]])
print('a=\n', a)
b = a * 10
print('b=\n', b)

a=
 [[1 2 3]
 [4 5 6]]
b=
 [[10 20 30]
 [40 50 60]]


In [21]:
# add and substract two matrices
sum_mat = a + b
print(sum_mat)
diff_mat = a - b
print(diff_mat)

[[11 22 33]
 [44 55 66]]
[[ -9 -18 -27]
 [-36 -45 -54]]


The multiplication operator \* is implemented in a different way from linear algebra: For two matrices with 
same shapes the elements at the same coordinates are multiplied: c[i, j] = a[i, j] * b[i, j]. This is called pointwise multiplication, or Hadamard product, and it is often used in signal processing and machine learning

In [22]:
# multiplication by * leads to Hadamard product: c[i, j] = a[i, j] * b[i, j]
c = a * b
print(c)
for i in range(c.shape[0]):  # c.shape[0] = number of rows of matrix c
    for j in range(c.shape[1]): # c.shape[1] = number of columns of matrix c
        print(c[i, j] == a[i, j] * b[i, j])

[[ 10  40  90]
 [160 250 360]]
True
True
True
True
True
True


The above operations are using linear algebra libraries, which are optimized for the current microprocessors. It is recommended to use them instead of (nested) for cycles:

In [23]:
# create matrices
matrix_shape = (100, 100)
a_big = np.random.random(matrix_shape)
b_big = np.random.random(matrix_shape)

In [24]:
%%timeit
c_big = np.empty_like(a_big)
for i in range(c_big.shape[0]):
    for j in range(c_big.shape[1]):
        c_big[i, j] = a_big[i, j] * b_big[i, j]

5.15 ms ± 178 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [25]:
%%timeit
c_big = a_big * b_big

5.95 µs ± 297 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
# 'raising to power' using ** : each element of the matrix is individually raised to that power.
print('initial matrix:\n', a)
a_to_the_power_of_2 = a ** 2
print('after squaring each component:\n', a_to_the_power_of_2)
power_3 = np.power(a, 3)
print('after raising to the power of 3:\n', power_3)

initial matrix:
 [[1 2 3]
 [4 5 6]]
after squaring each component:
 [[ 1  4  9]
 [16 25 36]]
after raising to the power of 3:
 [[  1   8  27]
 [ 64 125 216]]


You can use the / operator to get pointwise division (element by element) of two matrices:

In [27]:
print('a=', a)
print('b=', b)
print('a/b=', a/b)

a= [[1 2 3]
 [4 5 6]]
b= [[10 20 30]
 [40 50 60]]
a/b= [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [28]:
# raising a square matrix to a power, as defined in linear algebra
square_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
pow_3 = np.linalg.matrix_power(square_matrix, 3)
print(pow_3)

[[ 468  576  684]
 [1062 1305 1548]
 [1656 2034 2412]]


If you call a NumPy numerical function on an ndarray, the result will be an ndarray of same shape as the original one. Its elements are computed by applying the function on each of the initial matrix componets, one by one:

In [29]:
x = np.arange(6).reshape(2, 3)
print(x)
y = np.exp(x)
print(f'e^x=\n{y}')
assert x.shape == y.shape
for i in range(0, x.shape[0]):
    for j in range(0, x.shape[1]):
        assert y[i, j] == np.exp(x[i, j])

[[0 1 2]
 [3 4 5]]
e^x=
[[  1.           2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003 148.4131591 ]]


In [30]:
# linear-algebra style matrix product
a = np.random.rand(3, 5)
b = np.random.rand(5, 10)
assert a.shape[1] == b.shape[0]
c = np.dot(a, b)

# equivalent form
c = a.dot(b)
assert a.shape[0] == c.shape[0] and b.shape[1] == c.shape[1]

# or even shorter:
c = a@b

NumPy defines a whole pletora of functions: `all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where` - [docs here](https://docs.scipy.org/doc/numpy-dev/reference/generated/).

## Indexing 

So far, we used individual indices to refer to particular elements in a NumPy array:
```python
vector[index]
# or
matrix[i, j]
```

In [31]:
vector = np.arange(10)
print(vector)
print('vector[4]={0}'.format(vector[4]))

[0 1 2 3 4 5 6 7 8 9]
vector[4]=4


In [32]:
matrix = np.arange(12).reshape(3, 4)
print(matrix)
print(matrix[2, 1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
9


For a matrix one can use indices as:
```python
m[i][j] 
```
but this is innefficient compared to `m[i,j]`, as in the former case a temporary copy of row `i` is done, and from this one the element at index `j` is retrieved.

By using `slicing`, one can refer to a whole subset of elements. For example, one gets for vectors:

In [33]:
vector = 10 * np.arange(10)
print(vector)
print(vector[2:6]) # note that the rightmost boundary is not used for selection; 
# i.e. the elements are retrieved up to index 6-1

[ 0 10 20 30 40 50 60 70 80 90]
[20 30 40 50]


In [34]:
indices = [1, 3, 2, 7]
print(vector)
print(vector[indices])

[ 0 10 20 30 40 50 60 70 80 90]
[10 30 20 70]


In [35]:
# the same index can be repeated:
indices = [1, 3, 2, 3, 3, 3, 3]
print(vector)
print(vector[indices])

[ 0 10 20 30 40 50 60 70 80 90]
[10 30 20 30 30 30 30]


In [36]:
# or we can use a sequence of indices, with initial/step/final value given
vector[2:8:2]

array([20, 40, 60])

For a matrix you can use:

In [37]:
matrix = 10 * np.arange(20).reshape(4, 5)
print(matrix)

print(matrix[1,])
# which is the same with the more explicit form:
print(matrix[1, :])

[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]]
[50 60 70 80 90]
[50 60 70 80 90]


In [38]:
print(matrix[1,])
# which is the same with the more explicit form:
print(matrix[1, :])

[50 60 70 80 90]
[50 60 70 80 90]


In [39]:
# you can slice indices, on any axis
matrix[1:3, :]

array([[ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140]])

In [40]:
# slicing on avery axis
matrix[1:3, 2:4]

array([[ 70,  80],
       [120, 130]])

### Logical indexing

You can execute logical operations against the elements of a NumPy array. As a result of this, you will obtain an ndarray of the same shape as the initial array, filled in with `True` and `False`. The exact boolean value is the result of the logical operation on the values at the same positions:

In [41]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print(a > 2)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


Furthermore, the resulted ndarray can be used for indexing. You will get only those elements for which the boolean operation yielded `True`:

In [42]:
larger_than_2 = a > 2
print(a[larger_than_2])

# direct selection
print(a[a>2])

# Note that the initial shape of a is lost. Can you explain why?

[3 4 5 6]
[3 4 5 6]


For joint conditions one can use boolean operators. For example, to select elements which are larger than 2, but smaller than 6, one writes:

In [43]:
a[np.logical_and(a > 2, a < 6)]

array([3, 4, 5])

Similar operators are: `np.logical_or`, `np.logical_not`, `np.logical_xor`.

A popular request for ndarrays is getting those FP elements which are defined - i.e. those which are not NaNs (NaN = not a number, values resulted due to invalid operations like: 0/0, np.sqrt(-1), np.log(-1), etc.):

In [44]:
tab = np.array([[1.0, 2.3, np.nan, 4], [10, np.nan, np.nan, 0]])
print(tab[~np.isnan(tab)])

[ 1.   2.3  4.  10.   0. ]


In all cases, indexing returns a view of the initial array. Modifications done on this view will actually update the underlying initial array:

In [45]:
print('Before:\n', tab)
tab[np.isnan(tab)] = 0.0
print('After:\n', tab)

Before:
 [[ 1.   2.3  nan  4. ]
 [10.   nan  nan  0. ]]
After:
 [[ 1.   2.3  0.   4. ]
 [10.   0.   0.   0. ]]


Logical indexing allows selection of the elements in an array whose contents is to be changed:

In [46]:
# even numbers are multiplied by 10, the other ones remain unchanged 
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print('Before update:\n', matrix)
matrix[matrix % 2 == 0] *= 10
print('After update:\n', matrix)

Before update:
 [[1 2 3 4]
 [5 6 7 8]]
After update:
 [[ 1 20  3 40]
 [ 5 60  7 80]]


You may perform update on a specific axis:

In [47]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.float32)
print('Before update:\n', matrix)
# columns 0, 2, 3 will be updated
bool_columns = [True, False, True, True]
matrix[:, bool_columns] = (matrix[:, bool_columns] +3 )/10
print('After update\n', matrix)

Before update:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
After update
 [[0.4 2.  0.6 0.7]
 [0.8 6.  1.  1.1]]


### Supplementary bibliography 
1. https://docs.scipy.org/doc/numpy-1.13.0/glossary.html
1. https://engineering.ucsb.edu/~shell/che210d/numpy.pdf
1. http://www.scipy-lectures.org/intro/numpy/numpy.html#indexing-and-slicing

## Broadcasting

Broadcasting allows operations with matrices of incompatible dimensions, under specific circumstances. For example, following the mathematical definition of matrix addiction, the matrices `a` and `b`b below could not be added:

In [48]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([0.0,1.0,2.0])  

print('a=\n{0}\n'.format(a))
print('b=\n{0}\n'.format(b))

a=
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]

b=
[0. 1. 2.]



Through broadcasting, the matrix `b` is automatically extended through copy/paste of its line:
![broadcast](./images/broadcast1.png)

In [49]:
# broadcasting
result = a + b
print('result=\n{0}\n'.format(result))

result=
[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]



Broadcasting is done if some conditions are fulfilled. When one operates on two matrices, NumPy compares the sizes on each dimension, starting with the last dimension. Two dimensions are compatible when: 

1. they are equal, or
1. one of them is 1

The rules above are not fulfilled, for example, by:

![Broadcat imposibil](./images/broadcast2.png)
or for the case below:

In [50]:
x = np.arange(4)
y = np.ones(5)
print(x.shape, y.shape)

#print(x+y) # ValueError: operands could not be broadcast together with shapes (4,) (5,) 

(4,) (5,)


In [51]:
x = np.arange(4).reshape(4, 1)
print('x shape: ', x.shape)
print('x:\n', x)

x shape:  (4, 1)
x:
 [[0]
 [1]
 [2]
 [3]]


In [52]:
y = np.arange(5).reshape(1, 5)
print('y shape: ', y.shape)
print('y:\n', y)

y shape:  (1, 5)
y:
 [[0 1 2 3 4]]


In [53]:
z = x + y
print('z shape:', z.shape)
print('z\n', z)

z shape: (4, 5)
z
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


The broadcast internally produced the following two matrices right before doing the addition:

In [54]:
# clone x and create multiple identical columns:
x_broadcast = np.tile(x, (1, 5))
x_broadcast

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [55]:
# clone y and create multiple identical rows:
y_broadcast = np.tile(y, (4, 1))
y_broadcast

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

Now, the two matrices can be added:

In [56]:
z_broadcast = x_broadcast + y_broadcast
assert np.alltrue(z_broadcast == z)

### Broadcast practical example

([Source](https://eli.thegreenplace.net/2015/broadcasting-arrays-in-numpy/)) For specific food types, we decompose them in fats, carbs, proteins, all of them weighted in grams. We want to convert each food type components into calories, by using multiplicative constants:
1. calories for fats = 9 * fats in grams
1. calories for proteins = 4 * protein grams
1. calories for carbs = 4 * carbs in grams

![tabel portii](./images/broadcast3.png)

The multiplication is computed by broadcasting:

In [57]:
weights = np.array([
  [0.3, 2.5, 3.5],
  [2.9, 27.5, 0],
  [0.4, 1.3, 23.9],
  [14.4, 6, 2.3]]
)

cal_per_g = np.array([9, 4, 4])

# broadcasting
calories = weights * cal_per_g

print('Calories:\n', calories)

Calories:
 [[  2.7  10.   14. ]
 [ 26.1 110.    0. ]
 [  3.6   5.2  95.6]
 [129.6  24.    9.2]]


### Supplementary bibliography 

[Basic broadcasting: https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc

http://cs231n.github.io/python-numpy-tutorial/#numpy-broadcasting

## Vectorized computation

Motivational presentation: https://www.kdnuggets.com/2017/11/forget-for-loop-data-science-code-vectorization.html 

### Example

We have 2 collections of numbers: the first one contains distances, the second one is time requested to cover them. We want to compyte the speed. We will present two approaches: a classical `for` cycle, and vectorized computation.

In [58]:
distances = [10, 20, 23, 14, 33, 45]
durations = [0.3, 0.44, 0.9, 1.2, 0.7, 1.1]

In [59]:
# Version 1: traditional cycle
speeds = []
for i in range(len(distances)):
    speeds.append(distances[i] / durations[i])
    
print('Speed computed by for loop: ', speeds)

Speed computed by for loop:  [33.333333333333336, 45.45454545454545, 25.555555555555554, 11.666666666666668, 47.142857142857146, 40.90909090909091]


In [60]:
# Version 2: vectorization
# Vectorization works on vector/matrices, the first step is to convert lists to NumPy arrays

distances_array = np.array(distances)
durations_array = np.array(durations)

# We use NumPy operations which work with full matices. The C code  
# uses Single Instruction Multiple Data (SIMD) facilities from the CPU. 

speeds_array = distances_array/durations_array

print(f'speed computed by vectorization: {speeds_array}')

assert np.alltrue(speeds_array == speeds)

speed computed by vectorization: [33.33333333 45.45454545 25.55555556 11.66666667 47.14285714 40.90909091]


### Benefits of vectorization

1. Fast(er) execution
1. Short and often more readable code

Example: let us compute
$$
\sum\limits_{i=0}^{N-1} (i\%3-1) \cdot i
$$

In [61]:
# Python funciton with non-vectorized computation (`for` cycle)

N = 100000

def func_python(N):
    d = 0.0
    for i in range(N):
        d += (i%3-1) * i
    return d

print(func_python(N))

-33333.0


In [62]:
%timeit func_python(N)

12.7 ms ± 351 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [63]:
# function with vectorized computation

def func_numpy(N):
    i_array = np.arange(N)
    return ((i_array % 3 - 1 ) * i_array).sum()

print(func_numpy(N))

-33333


In [64]:
%timeit func_numpy(N)

1.06 ms ± 33.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Most operations and NumPy functions work for any number of values, element by element - they are also called universal functions. They are optimized to work with SIMD devices. The following operators and functions are efficiently working with arrays:

- arithmetic operators: + - * / // % **
- bitwise operators: & | ~ ^ >> <<
- comparisons: < <= > >= == !=
- math functions: np.sin, np.log, np.exp, ...
- special scipy functions: `scipy.special.*`

Although some NumPy functions are already provided by Python - e.g. `sum`, `min`, `mean` -ufuncs are much faster:

In [65]:
from random import random
c = [random() for i in range(N)]

In [66]:
# Python builtin function
%timeit sum(c)

545 µs ± 93.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [67]:
# NumPy vectorized: prepare the NumPy array
c_array = np.array(c)

In [68]:
# NumPy vectorized: use ufunc sum
%timeit c_array.sum()

63.3 µs ± 5.13 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Vectorization exercises

#### Adding filtered numbers

For a given list of numbers, compute the sum of contained values which are in a specified interval $[a, b]$. 

In [69]:
n = 100000000
numbers = [int(1000 * random()) for _ in range(n)]

a, b = 100, 500

A direct Python implementatin would be:

In [70]:
%%timeit
s = 0
for x in numbers:
    if a <= x <= b:
        s += x

9.67 s ± 1.03 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


Using comprehension:

In [71]:
%%timeit
s = sum(x for x in numbers if a <= x <= b)

8.9 s ± 633 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Python built-in filtering:

In [72]:
%%timeit
s = sum(filter(lambda x: a <= x <= b, numbers))

12.8 s ± 366 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Python vectorization - build ndarray vector, then find indices of interest:

In [73]:
np_numbers = np.array(numbers)

In [74]:
%%timeit
ind_a = np_numbers >= a
ind_b = np_numbers <= b
s = np_numbers[np.logical_and(ind_a, ind_b)].sum()

942 ms ± 69.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### Counting the number of sign changes

For a given vector with positive an negative values, count how many times the values are changing their signs in consecutive positions. It is guaranteed that the vector does not contain 0 values. 

Example: for input 
$$
v = [-1, 2, 3, -3, 1, -1, 1]
$$
the 4 sign of the values change at positions (0, 1), (2, 3), (3, 4), (4, 5), (5, 6). The requested answer is 5.

In [75]:
n = 1000000
v = np.random.randint(-10, 10, n)
# replace 0 values with random -1 or +1
v[v==0] = np.random.randint(0, 2) * 2 - 1 # the initial random values {0, 1} are changed to {0*2-1, 1*2-1} = {-1, 1} 
assert 0 == (v == 0).sum()

The Python-base approach is straightforward:

In [76]:
%%timeit
sign_changes = 0
for i in range(1, len(v)):
    sign_changes += v[i-1] * v[i] < 0

2.51 s ± 170 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


The vectorized solution is:

In [77]:
%%timeit
# get the signs of the values
signs = np.sign(v)
# compute the difference between succesive values. Two successive equal signs produce 0, different signs produce -2 or +2
first_order_difference = np.diff(signs)
# find non zero positions
positions_not_0_in_diff = np.where(first_order_difference)[0]
# the number of non-zero positions is the requested value
sign_changes = len(positions_not_0_in_diff)
# sign_changes = len(np.where(np.diff(np.sign(v)))[0])

23.4 ms ± 4.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### Cumulative sum of values in a vector

Given a vector v[0..n-1], find the cumulative sum of its values: s=[v[0], v[0]+v[1], v[0]+v[1]+v[2], ..., v[0]+v[1]+...+v[n-1]]

In [78]:
n = 10000000
v = np.random.rand(n)

We will use the obvious relation:
$$
s[i] = 
\begin{cases}
v[0] & i =0 \\
s[i-1] + v[i] & i> 0
\end{cases}
$$

The unvectorized version is:

In [79]:
%%timeit
s = np.empty(n)
s[0] = v[0]
for i in range(1, n):
    s[i] = s[i-1] + v[i]

3.69 s ± 54.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


For the vectorize version, we mention that NumPy offers a function specifically for this, called `cumsum`. Its documentation is found [here](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html).

In [80]:
%%timeit
s = np.cumsum(v)

46.6 ms ± 1.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Another approach is based on the accumulate extension introduced by NumPy for any universal function, as seen [here](https://numpy.org/doc/stable/reference/generated/numpy.ufunc.accumulate.html). The 

In [81]:
%%timeit
s = np.add.accumulate(v)

47.9 ms ± 2.96 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### Finding the closest pair of points

We have $n$ points in 2D space. Their coordinates are given in vectors **x** and **y**, respectively. Compute the closest pair of points, using Euclidean distance:
$$
d^2((x_i, y_i), (x_j, y_j)) = (x_i-x_j)^2 + (y_i-y_j)^2
$$

In [82]:
n = 2000
x = np.random.random(size = n)
y = np.random.random(size = n)

In [83]:
# Version 1: compute the matrix `d` of pairwise distances. d[i, j] will store the square of the distance 
# between points of coordinates (xi, yi) and (xj, yj), respectively.

In [84]:
%%timeit

d = np.empty((n, n))
for i in range(n):
    for j in range(i, n):
        d[i, j] = d[j, i] = (x[i] - x[j])**2 + (y[i]-y[j])**2

3.16 s ± 72.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [85]:
# compute the indices i and j, i != j, for which the distance is minimized

def closest_pair(mat):
    n = mat.shape[0]
    # distance between a point and itself is always 0; we will exclude these cases by setting infinity on the main diagonal of distances
    i = np.arange(n)
    mat[i, i] = np.inf
    pos_flatten = np.argmin(mat)
    return pos_flatten // n, pos_flatten % n
    

In [86]:
# Version 2: vectorized computation and broadcasting

In [87]:
%%timeit

dx = (x[:, np.newaxis] - x[np.newaxis, :]) ** 2
dy = (y[:, np.newaxis] - y[np.newaxis, :]) ** 2

d = dx + dy

70.1 ms ± 9.52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Supplementary bibliography 

[https://speakerdeck.com/jakevdp/losing-your-loops-fast-numerical-computing-with-numpy-pycon-2015](https://speakerdeck.com/jakevdp/losing-your-loops-fast-numerical-computing-with-numpy-pycon-2015)

[Losing your Loops Fast Numerical Computing with NumPy](https://www.youtube.com/watch?v=EEUXKG97YRw)